app = 'firebolt'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.concurrency]
  type = "requests"
  hard_limit = 99999999
  soft_limit = 99999

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
