# fly.toml app configuration file generated for firebolt on 2024-03-09T13:39:39+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'firebolt'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
